# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c5cbcb22247e0b0bd5914e82ed3a31d45fbe67c8665815cf561483af240117994ce4b60044394ab92e56505a5748c8108754829ac482fd52e7a8882df736757

test:
  secret_key_base: f4e220546e0113d46fc91d07cb984d554d779fabe2d959228c49bdb8311fb50f6fc772b6a29e8ac2a631f42c1205eb3d171389419d0ffaa9311cc622c8c172c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
